config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:  'posts#index'
    resources :mantweets do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :show, :edit, :update, :destroy]
    end
    resources :womantweets do
      resource :secondfavorites, only: [:create, :destroy]
      resources :secondcomments, only: [:create, :show, :edit, :update, :destroy]
    end
    resources :users
    resources :posts, only:[:index]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :mantweet
  belongs_to :user


  with_options presence: true do
    validates :text
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :mantweet
  validates_uniqueness_of :mantweet_id, scope: :user_id
end

app/models/mantweet.rb
class Mantweet < ApplicationRecord

  attachment :image
  belongs_to :user
  has_many :comments
  has_many :favorites, dependent: :destroy

  
  with_options presence: true do
    validates :title
    validates :body
  end

end

app/models/post.rb
class Post < ApplicationRecord

end

app/models/secondcomment.rb
class Secondcomment < ApplicationRecord
  belongs_to :womantweet
  belongs_to :user

  with_options presence: true do
    validates :text
  end
  
end

app/models/secondfavorite.rb
class Secondfavorite < ApplicationRecord
  belongs_to :user
  belongs_to :womantweet
  validates_uniqueness_of :womantweet_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
  end
      
  has_many :comments
  has_many :mantweet, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :womantweet, dependent: :destroy
  has_many :secondfavorites, dependent: :destroy
  attachment :profile_image

  def already_favorited?(mantweet)
    self.favorites.exists?(mantweet_id: mantweet.id)
  end

  def already_secondfavorited?(womantweet)
    self.secondfavorites.exists?(womantweet_id: womantweet.id)
  end
     

end

app/models/womantweet.rb
class Womantweet < ApplicationRecord


  attachment :image
  belongs_to :user
  has_many :secondcomments
  has_many :secondfavorites, dependent: :destroy


  with_options presence: true do
    validates :title
    validates :body
    validates :image_id
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    mantweet = Mantweet.find(params[:mantweet_id])
    @comment = mantweet.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  # def show
  #   @comments = Comment.find(params[:id])
  # end

  # def edit
  #   @comments = Comment.find(params[:id])
  # end

  # def update
  #   @comments = Comment.find(params[:id])
  #   @comments.update(comment_params)
  #   redirect_to mantweet_comment_path
  # end

  # def destroy
  #   @comments = Comment.find(params[:id])
  #   @comments.destroy
  #   redirect_to mantweet_path
  # end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, mantweet_id: params[:mantweet_id])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = current_user.favorites.create(mantweet_id: params[:mantweet_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @mantweet = Mantweet.find(params[:mantweet_id])
    @favorite = current_user.favorites.find_by(mantweet_id: @mantweet.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/mantweets_controller.rb
class MantweetsController < ApplicationController

  before_action :set_mantweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create]





  def index
    @mantweet = Mantweet.all.order("created_at DESC")
  end

  def new
    @mantweet = Mantweet.new
  end

  def create
    @mantweet = Mantweet.new(mantweet_params)
    if @mantweet.save
      redirect_to mantweets_path
    else
      render :new
    end
  end

  def show
    @comments = @mantweet.comments
    @comment = @mantweet.comments.build
  end

  def edit
  end

  def update 
    if @mantweet.update(mantweet_params)
      redirect_to mantweet_path
    else
      render :edit
    end
  end

  def destroy
    if @mantweet.destroy
      redirect_to mantweets_path
    else
      render :index
    end
  end

  

  private
  
    def mantweet_params
      params.require(:mantweet).permit(:title, :body, :image).merge(user_id: current_user.id)
    end

    def set_mantweet
      @mantweet = Mantweet.find(params[:id])
    end

    


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/mantweets_helper.rb
module MantweetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/secondcomments_helper.rb
module SecondcommentsHelper
end

app/helpers/secondfavorites_helper.rb
module SecondfavoritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/womantweets_helper.rb
module WomantweetsHelper
end

app/views/comments/edit.html.erb
<%= render "shared/header" %>

<div class="mt-edit">
<div class="mt">
      <% unless @comments.user.blank? %>
      <figure class="image is-48x48">
        <%= attachment_image_tag @comments.mantweet.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
      </figure>
        <a href="<%= user_path(@comments.user_id) %>">
          <div class="mt-3" style="color: #333;">
            <%= @comments.user.nickname unless @comments.user.blank? %>
          </div>
        </a>
            <% end %>
      <br />
      <a href="<%= mantweet_comment_path(:id) %>">
        <div class="mt-4" style="color: #333;">
          <%= @comments.text %>
        </div>
      </a>
    </div>
    <br />
</div>

      <%= form_for @comment do |f| %>
      <%= f.text_area :text, class: "form-control", rows: 5 %>
      <%= button_tag type: "submit", class: "btnbtn-successfloat-rightmt-1" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>

app/views/comments/show.html.erb
<%= render "shared/header" %>


<div class="mt-edit">
<div class="mt">
      <% unless @comments.user.blank? %>
      <figure class="image is-48x48">
        <%= attachment_image_tag @comments.mantweet.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
      </figure>
        <a href="<%= user_path(@comments.user_id) %>">
          <div class="mt-3" style="color: #333;">
            <%= @comments.user.nickname unless @comments.user.blank? %>
          </div>
        </a>
            <% end %>
      <br />
      <a href="<%= mantweet_comment_path(:id) %>">
        <div class="mt-4" style="color: #333;">
          <%= @comments.text %>
        </div>
      </a>
    </div>
    <br />
</div>

<% if user_signed_in? && current_user.id == @comments.user_id %>
  <div class="show-btn">
    <%= link_to '編集', edit_mantweet_comment_path(@comment) , method: :get, class: "far fa-edit", style="font-size: 30px; color: #333; margin-right: 30px;" %> 
    <%= link_to '削除', mantweet_comment_path , method: :delete, class:'far fa-trash-alt' %>
  </div>
  <% end %>

app/views/mantweets/edit.html.erb
<%= render "shared/header" %>

<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title" style="color: black;">
        スタイル編集
      </h1>
    </div>
  </div>
</section>

<% if @mantweet.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @mantweet.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-13">
        <%= form_for @mantweet do |f| %>
          <div class="field">
            <%= f.label :title, "スタイル名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "説明", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>
          <%= f.submit '更新', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/mantweets/index.html.erb
<%= render "shared/header" %>

<div class="man-toppage">
  <h1>Man</h1>
</div>

<div class="man-tweetbtn">
<%= link_to "投稿する", new_mantweet_path(@mantweet), class: "far fa-plus-square", style: "color: skyblue;" %>
</div>

 <section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @mantweet.each do |mantweet| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to mantweet_path(mantweet) do %>
                  <%= attachment_image_tag mantweet, :image %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= attachment_image_tag mantweet.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%=link_to mantweet.user.nickname, user_path(mantweet.user) %></div>
                </div>
              </div>

              <div class="content">
                <time><%= mantweet.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/mantweets/new.html.erb
<%= render "shared/header" %>

<% if @mantweet.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@mantweet.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @mantweet.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-14">
        <%= form_for @mantweet do |f| %>
          <div class="field">
            <%= f.label :title, "スタイル名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "説明", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/mantweets/show.html.erb
<%= render "shared/header" %>

<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title" style="color: black;">
        スタイル詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= attachment_image_tag @mantweet, :image %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-5"><%= @mantweet.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>説明</th>
                </tr>
                <tr>
                  <td><%= simple_format @mantweet.body %></td>
                </tr>
              </table>
              <% if @mantweet.user.id == current_user.id %>
                <%= link_to "編集", edit_mantweet_path(@mantweet), class: "button is-success" %>
                <%= link_to "削除", mantweet_path(@mantweet), method: :delete, class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
          <%= @mantweet.user.nickname %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @mantweet.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@mantweet.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @mantweet.user.nickname %> さんのページへ
          <% end %>
        </article>
      </div>
    </div>
  </div>
</section>

<div class="favorite">
<% if current_user.already_favorited?(@mantweet) %>
            <%= link_to mantweet_favorites_path(@mantweet), method: :delete do %>
              <i class="fas fa-heart heart_red">
              <%= @mantweet.favorites.count %></i>
            <% end %>
            
          <% else %>
            <%= link_to mantweet_favorites_path(@mantweet), method: :post do %>
              <i class="far fa-heart">
              <%= @mantweet.favorites.count %></i>
            <% end %>
            
          <% end %>

<div class="comment-wrapper border-top mb-10">
  <p class="mt-5">コメント一覧</p>
  <% @comments.each do |c| %>
    <div class="mt">
      <% unless c.user.blank? %>
      <figure class="image is-48x48">
        <%= attachment_image_tag c.mantweet.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
      </figure>
        <a href="<%= user_path(c.user_id) %>">
          <div class="mt-3" style="color: #333;">
            <%= c.user.nickname unless c.user.blank? %>
          </div>
        </a>
            <% end %>
      <br />
      <a href="<%= mantweet_comment_path(:id) %>"></a>
        <div class="mt-4">
          <%= c.text %>
        </div>
    </div>
    <br />
  <% end %>
  <% if user_signed_in? %>
    <%= form_with(model: [@mantweet, @comment], local: true) do |f| %>
      <%= f.text_area :text, class: "form-control", rows: 5 %>
      <%= button_tag type: "submit", class: "btnbtn-successfloat-rightmt-1" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>
</div>      

app/views/posts/index.html.erb
<%= render "shared/header" %>

<div class="main">


  <div class="back-content">
    <% if user_signed_in? %>
    <div class="log-in">
      <h1 class="login">Welcome</h1>
    </div>
    <% else %>
    <div class="log-in">
      <h1 class="login">Login</h1>
    </div>
    <% end %> 
  </div>
</div>
  
  <div class="images">

    <div class="man-image">
    </div>

    <div class="woman-image">
    </div>

  </div>


  <div class="contents">

    <div class="man-content">

      <div class="man-menu" id="man-lists">
        <h1 class="gender-man">Man</h1>
      </div> 
      
    </div>


    <div class="woman-content">

      <div class="woman-menu" id="woman-lists">
        <h1 class="gender-woman">Woman</h1>
      </div>

    </div>
  </div>

  <div class="lists">

    <div class="man-lists">
      <ul class="man-list" id="man-pull-down">

        <li><a href="/mantweets" class="man-list1"><span>H</span><span>a</span><span>i</span><span>r</span><span>S</span><span>t</span><span>y</span><span>l</span><span>e</span></a>
        </li>
      </ul>
    </div>

    <div class="woman-lists">
      <ul class="woman-list" id="woman-pull-down">
        <li><a href="/womantweets" class="woman-list1"><span>H</span><span>a</span><span>i</span><span>r</span><span>S</span><span>t</span><span>y</span><span>l</span><span>e</span></a>
        </li>
      </ul>
    </div>


  </div>




  <%# スライドショーランキング %>
    <h2 style="font-size: 100px; color: #333; margin-left: 770px; margin-bottom: 100px;">Pic Up✨</h2>
    <%# スライドショー配置 %>
      <ul class="slider">
        <li>man<%= link_to image_tag("original.png"), "https://beauty-sharing.herokuapp.com/mantweets/1" %>
      </ul>

app/views/users/edit.html.erb
<%= render "shared/header" %>

<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title" style="color:black">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>


<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-13">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :nickname, "ユーザー名", class: "label" %>
            <%= f.text_field :nickname, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<%= render "shared/header" %>

<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title" style="color:black">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.nickname %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.mantweet.each do |mantweet| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to mantweet_path(mantweet) do %>
                  <%= attachment_image_tag mantweet, :image, fallback: "no-image.png" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to mantweet_path(mantweet), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    この投稿を見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_mantweet_path(mantweet), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit" style="none"></i>
                      </span>
                      この投稿を編集する
                    <% end %>
                    <%= link_to mantweet_path(mantweet), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      この投稿を削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= mantweet.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>












<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.womantweet.each do |womantweet| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to womantweet_path(womantweet) do %>
                  <%= attachment_image_tag womantweet, :image, fallback: "no-image.png" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to womantweet_path(womantweet), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    この投稿を見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_womantweet_path(womantweet), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit" style="none"></i>
                      </span>
                      この投稿を編集する
                    <% end %>
                    <%= link_to womantweet_path(womantweet), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      この投稿を削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= womantweet.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>