config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:  'posts#index'
    resources :mantweets do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :show, :edit, :update, :destroy]
    end
    resources :womantweets do
      resource :secondfavorites, only: [:create, :destroy]
      resources :secondcomments, only: [:create, :show, :edit, :update, :destroy]
    end
    resources :users
    resources :posts, only:[:index]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :mantweet
  belongs_to :user


  with_options presence: true do
    validates :text
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :mantweet
  validates_uniqueness_of :mantweet_id, scope: :user_id
end

app/models/mantweet.rb
class Mantweet < ApplicationRecord

  attachment :image
  belongs_to :user
  has_many :comments
  has_many :favorites, dependent: :destroy

  
  with_options presence: true do
    validates :title
    validates :body
  end

end

app/models/post.rb
class Post < ApplicationRecord

end

app/models/secondcomment.rb
class Secondcomment < ApplicationRecord
  belongs_to :womantweet
  belongs_to :user

  with_options presence: true do
    validates :text
  end
  
end

app/models/secondfavorite.rb
class Secondfavorite < ApplicationRecord
  belongs_to :user
  belongs_to :womantweet
  validates_uniqueness_of :womantweet_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
  end
      
  has_many :comments
  has_many :mantweet, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :womantweet, dependent: :destroy
  has_many :secondfavorites, dependent: :destroy
  attachment :profile_image

  def already_favorited?(mantweet)
    self.favorites.exists?(mantweet_id: mantweet.id)
  end

  def already_secondfavorited?(womantweet)
    self.secondfavorites.exists?(womantweet_id: womantweet.id)
  end
     

end

app/models/womantweet.rb
class Womantweet < ApplicationRecord


  attachment :image
  belongs_to :user
  has_many :secondcomments
  has_many :secondfavorites, dependent: :destroy


  with_options presence: true do
    validates :title
    validates :body
    validates :image_id
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    mantweet = Mantweet.find(params[:mantweet_id])
    @comment = mantweet.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  # def show
  #   @comments = Comment.find(params[:id])
  # end

  # def edit
  #   @comments = Comment.find(params[:id])
  # end

  # def update
  #   @comments = Comment.find(params[:id])
  #   @comments.update(comment_params)
  #   redirect_to mantweet_comment_path
  # end

  # def destroy
  #   @comments = Comment.find(params[:id])
  #   @comments.destroy
  #   redirect_to mantweet_path
  # end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, mantweet_id: params[:mantweet_id])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = current_user.favorites.create(mantweet_id: params[:mantweet_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @mantweet = Mantweet.find(params[:mantweet_id])
    @favorite = current_user.favorites.find_by(mantweet_id: @mantweet.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :email, :profile, :profile_image)
  end
end

app/controllers/womantweets_controller.rb
class WomantweetsController < ApplicationController
  before_action :set_mantweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create]





  def index
    @womantweet = Womantweet.all.order("created_at DESC")
  end

  def new
    @womantweet = Womantweet.new
  end

  def create
    @womantweet = Womantweet.new(womantweet_params)
    if @womantweet.save
      redirect_to womantweets_path
    else
      render :new
    end
  end

  def show
    @secondcomments = @womantweet.secondcomments
    @secondcomment = @womantweet.secondcomments.build
  end

  def edit
  end

  def update 
    if @womantweet.update(womantweet_params)
      redirect_to womantweet_path
    else
      render :edit
    end
  end

  def destroy
    if @womantweet.destroy
      redirect_to womantweets_path
    else
      render :index
    end
  end

  

  private
  
    def womantweet_params
      params.require(:womantweet).permit(:title, :body, :image).merge(user_id: current_user.id)
    end

    def set_mantweet
      @womantweet = Womantweet.find(params[:id])
    end

    


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/mantweets_helper.rb
module MantweetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/secondcomments_helper.rb
module SecondcommentsHelper
end

app/helpers/secondfavorites_helper.rb
module SecondfavoritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/womantweets_helper.rb
module WomantweetsHelper
end

app/views/womantweets/edit.html.erb
<%= render "shared/header" %>

<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title" style="color: black;">
        スタイル編集
      </h1>
    </div>
  </div>
</section>

<% if @womantweet.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@womantweet.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @womantweet.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-13">
        <%= form_for @womantweet do |f| %>
          <div class="field">
            <%= f.label :title, "スタイル名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "説明", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>
          <%= f.submit '更新', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/womantweets/index.html.erb
<%= render "shared/header" %>



<div class="woman-toppage">
  <h1>Woman</h1>
</div>

<div class="woman-tweetbtn">
<%= link_to "投稿する", new_womantweet_path(@womantweet), class: "far fa-plus-square", style: "color:  violet;" %>
</div>

 <section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @womantweet.each do |womantweet| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to womantweet_path(womantweet) do %>
                  <%= attachment_image_tag womantweet, :image %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= attachment_image_tag womantweet.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%=link_to womantweet.user.nickname, user_path(womantweet.user) %></div>
                </div>
              </div>

              <div class="content">
                <time><%= womantweet.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/womantweets/new.html.erb
<%= render "shared/header" %>

<% if @womantweet.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@womantweet.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @womantweet.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-14">
        <%= form_for @womantweet do |f| %>
          <div class="field">
            <%= f.label :title, "スタイル名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "説明", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/womantweets/show.html.erb
<%= render "shared/header" %>

<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title" style="color: black;">
        スタイル詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= attachment_image_tag @womantweet, :image %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-5"><%= @womantweet.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>説明</th>
                </tr>
                <tr>
                  <td><%= simple_format @womantweet.body %></td>
                </tr>
              </table>
              <% if @womantweet.user.id == current_user.id %>
                <%= link_to "編集", edit_womantweet_path(@womantweet), class: "button is-success" %>
                <%= link_to "削除", womantweet_path(@womantweet), method: :delete, class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
          <%= @womantweet.user.nickname %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @womantweet.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@womantweet.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @womantweet.user.nickname %> さんのページへ
          <% end %>
        </article>
      </div>
    </div>
  </div>
</section>

<div class="favorite">
<% if current_user.already_secondfavorited?(@womantweet) %>
            <%= link_to womantweet_secondfavorites_path(@womantweet), method: :delete do %>
              <i class="fas fa-heart heart_red">
              <%= @womantweet.secondfavorites.count %></i>
            <% end %>
            
          <% else %>
            <%= link_to womantweet_secondfavorites_path(@womantweet), method: :post do %>
              <i class="far fa-heart">
              <%= @womantweet.secondfavorites.count %></i>
            <% end %>
            
          <% end %>

<div class="comment-wrapper border-top mb-10">
  <p class="mt-5">コメント一覧</p>
  <% @secondcomments.each do |c| %>
    <div class="mt">
      <% unless c.user.blank? %>
      <figure class="image is-48x48">
        <%= attachment_image_tag c.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
      </figure>
        <a href="<%= user_path(c.user_id) %>">
          <div class="mt-3" style="color: #333;">
            <%= c.user.nickname unless c.user.blank? %>
          </div>
        </a>
            <% end %>
      <br />
      <a href="<%= womantweet_secondcomment_path(:id) %>"></a>
        <div class="mt-4">
          <%= c.text %>
        </div>
    </div>
    <br />
  <% end %>
  <% if user_signed_in? %>
    <%= form_with(model: [@womantweet, @secondcomment], local: true) do |f| %>
      <%= f.text_area :text, class: "form-control", rows: 5 %>
      <%= button_tag type: "submit", class: "btnbtn-successfloat-rightmt-1" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>
</div>      